name: Vault Sync
on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'

jobs:
  sync:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Sync Files
        uses: BetaHuhn/repo-file-sync-action@latest
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          COMMIT_EACH_FILE: false
          PR_LABELS: "vault-sync"
