name: Vault Sync
on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'

jobs:
  sync:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # v3에서 v4로 업데이트
        with:
          token: ${{ secrets.PAT }}  # PAT 추가
          ref: ${{ github.head_ref }}
      
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "vault sync"
          commit_options: '--no-verify'
          file_pattern: '**/*'
