name: Vault Sync
on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'

jobs:
  sync:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "vault sync"
          commit_options: '--no-verify'
          file_pattern: '**/*'
