name: Vault Sync

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'

jobs:
  sync:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      
      - name: Check for changes
        id: changes
        run: |
          git diff --exit-code || echo "changes_detected=true" >> $GITHUB_OUTPUT
      
      - name: Git Auto Commit
        if: steps.changes.outputs.changes_detected == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "vault sync: ${{ github.event.head_commit.message }}"
          commit_options: '--no-verify'
          file_pattern: '**/*'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          push_options: '--force'
          skip_dirty_check: false
