name: Git Auto Commit

on:
  push:
    branches: [ "main" ]  # 트리거할 브랜치 지정

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "vault sync: ${{ github.event.head_commit.message }}"
          commit_options: '--no-verify'
          file_pattern: '**/*'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          push_options: '--force'
          skip_dirty_check: false
